### PR TITLE
SimpleViewGenerator didn't like Windows line-endings

### PR DESCRIPTION
**Pull request by harmanpa**
I had some Jackson deserialisation errors due to \r not being removed from files, this small change fixes it.

### CODE REVIEW

**Comment by YannRobert** [comment]
Hi thank you to this PR, could you please add some unit tests?

**Comment by harmanpa** [comment]
hi Yann, the best way to test is if the .js files loaded by SimpleViewGenerator have \r\n endings. If you build on Windows and have git set to use local line endings then this is the case, the unit tests in SimpleViewGeneratorTests failed for me for this reason (hence the fix!). However, if I manually add such endings, git will remove them again, so I'm not sure how to make a cross-platform test for it? Any thoughts?

**Comment by YannRobert** [comment]
@harmanpa Hi Peter, thank you for the comment.

Maybe you could use input content generated by Java code, or plain String literals like this :

```java
Reader reader = new StringReader("hello world\r\nthis is a dos content\r\n");
```
```java
Reader reader = new StringReader("hello world\nthis is a unix content\n");
```

**Comment by harmanpa** [comment]
Added a @BeforeClass method to SimpleViewGeneratorTest that duplicates some of the external resources with different line-endings, and tests that use them, so whatever platform the build is on it should test the alternative line-endings.

**Comment by harmanpa** [comment]
Removed the @BeforeClass approach and simplified to including in the annotations. This exposed fact that line-endings also break those, hence fixed SimpleViewGenerator to handle this.

**Comment by harmanpa** [comment]
@YannRobert is it possible to merge this? The project doesn't build on Windows without this change.

**Comment by YannRobert** [comment]
Hi @harmanpa sorry for the delay, I was not sure the PR was finished.

Could you please rebase with origin/master? and maybe squash your commits if needed?
If you can't, don't worry I'll do it.
I'll give some time to review the PR as soon as possible.

**Comment by harmanpa** [comment]
@YannRobert thanks, I've rebased to origin/master

**Comment by YannRobert** [comment]
@harmanpa I don't understand, when I run your version of the unit tests (```SimpleViewGeneratorTest```) without your version of the code change (in ```SimpleViewGenerator```), all tests are successful.
I would have expected at least one test fail.

**Comment by YannRobert** [comment]
@harmanpa please check PR #280 that is an alternative solution, that may be better and simpler.

It only replaces CR when it is followed immediately by LF, whereas your solution replaces CR anyways.
Also, tests are failing when the code is unchanged.

Also, I think supporting ```\r\n``` in inlined JSON String in annotation makes no sense. As the developer can as easily just use ```\n``` for readability.

Please tell me it this PR works for you.

**Comment by harmanpa** [comment]
@YannRobert I agree that including the line endings in the annotation doesn't really make sense, I was just trying to find a way of testing the replacement! I'm not sure it matters that I was removing all CR characters (actually I think leaving any CR or LF can cause problems) but #280 looks fine so I'm happy to close this PR in favour of that one. Thanks!

**Pull request closed without merging**
